[package]
name = "op_codesep_attack"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_wallet = { version="1.2.0",  features = ["file_store"] } 
bdk_bitcoind_rpc = "0.18.0"
bdk_file_store = "0.19.0"
bdk_sqlite = "0.2.0"
thiserror = "2.0.12"
rand = "0.9.0"
hex = "0.4.3"
serde_json = "1.0"
